pipeline {
    agent any
    stages {
        stage('Build Stage') {
            steps {
                sh 'g++ -o out PES2UG20CS398-1.cpp'
                echo "Build Successful"
            }
        }
        stage('Test Stage') {
            steps {
                sh './PES2UG20CS398-1'
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
